server:
  port: 8082

spring:
  application:
    name: client-two
  profiles:
    active: production
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import:
      optional:configserver:http://localhost:8888