server:
  port: 8081

spring:
  application:
    name: client-one
  profiles:
    active: production
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import:
      optional:configserver:http://localhost:8888

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - refresh
  endpoint:
    health:
      show-details: always
      enabled: true
