server:
  port: 8081

spring:
  application:
    name: client-one
  profiles:
    active: production
  cloud:
    config:
      uri: http://localhost:8888
  config:
    import:
      optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - refresh
  endpoint:
    health:
      show-details: always
      enabled: true
      
logging:
  level:
    root: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
